### ISSUE TITLE
[Consultancy]Does Pentaho Report can output Excel file with macro inside?

### ISSUE THREAD

**Issue by mike4gh** [pentaho/pentaho-reporting#1283]
We are trying to seek for the reporting solution, which requires to output the Excel files with Macro codes inside, e.g a drop-down list to select some specified values, once any value updates on the drop-down, it will trigger some defined macro code inside and then update related worksheet content.

Not sure whether it is the proper place to get this answered, but still looking forwards to the reply.

Cheers

**Comment by pamval** [comment]
Probably best if you ask that question in the Pentaho forums  at https://community.hitachivantara.com/community/products-and-solutions/pentaho/

Lots of people there who can assist.

Thanks
