### ISSUE TITLE
It is possible to use Pentaho-reporting in JDK 11

### ISSUE THREAD

**Issue by sathishnr98** [pentaho/pentaho-reporting#1383]
Previously I used Pentaho reports with JDK-1.8 now I can't able to use Pentaho reports in JDK-11

**Comment by smmribeiro** [comment]
@sathishnr98, versions 9.3 (LTS), 9.4, 9.5, 10.0 and 10.1 support **Java 8** and **Java 11**. As for version 10.2 (LTS), it supports **Java 11** and **Java 17**.
