### ISSUE TITLE
Use of Vulnerable Component: iText 2.7.1

### ISSUE THREAD

**Issue by JunweiZ** [pentaho/pentaho-reporting#1541]
This old version iText 2.7.1 has public known vulnerabilities.

**Comment by smmribeiro** [comment]
Closing this issue: com.lowagie:itext and com.lowagie:itext-rtf were dropped in favour of com.github.librepdf:openpdf and com.github.librepdf:openrtf with [pentaho-reporting#1621](https://github.com/pentaho/pentaho-reporting/commit/d042af6dc5357f3e4d55444b46a6572951f0d016) for 10.1 GA.
Thank you @JunweiZ
