### ISSUE TITLE
Apache Poi Vulnerability

### ISSUE THREAD

**Issue by MarijanaTR** [pentaho/pentaho-reporting#1549]
Apache poi library has 4 direct known high vulnerabilities [apachepoi](https://mvnrepository.com/artifact/org.apache.poi/poi/3.12)
Can the version be updated to at least 3.17 or higher?

**Comment by lucboudreau** [comment]
@MarijanaTR - Apache POI was upgraded to version 4.1.1 more than 2 years ago. Can you give us more details on where you are seeing a 3.X version?

https://github.com/pentaho/pentaho-reporting/blame/b74afabb970d933f4d4b8dd8094d60087b436443/pom.xml#L45

**Comment by smmribeiro** [comment]
@MarijanaTR and @lucboudreau: Apache POI was upgraded to 3.17 with [pentaho-reporting#1108](https://github.com/pentaho/pentaho-reporting/pull/1108) and this was for 8.1 GA...
We're using 4.1.1 since 9.2 GA.

**Comment by tiago-s-vieira-alb** [comment]
Hi, I think @MarijanaTR wanted to say POI 5.17 at least.
Can you upgrade to the last POI version? (25 November 2023 - POI 5.2.5 available)

**Comment by smmribeiro** [comment]
Closing this issue: Apache POI was upgraded to 5.2.5 with [pentaho-reporting#1649](https://github.com/pentaho/pentaho-reporting/commit/ea64ab7bea86827992eb2e9b45c754c0c08622ba) for 10.2 GA.
