### ISSUE TITLE
Pentaho Reporting Repositories are down

### ISSUE THREAD

**Issue by IOhacker** [pentaho/pentaho-reporting#1625]
Hello,

The Pentaho Reporting Repositories are down https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/

Is there any mirror?

Regards

**Comment by evaldasu** [comment]
Commenting to raise awareness because I'm also blocked by this issue.

**Comment by lursel** [comment]
Same here, would love to hear an update. Seems that the service is unavailable due to an expired trial license.

**Comment by CodeOnCoffee** [comment]
Repository seems to be up now. Please try it again.

**Comment by evaldasu** [comment]
> Repository seems to be up now. Please try it again.

At the moment of writing this I'm still receiving 503 and when navigating to the failing resource URL on the browser I get "Trial license expired!".

**Comment by lursel** [comment]
Still down as of today due to the expired license.

**Comment by CodeOnCoffee** [comment]
Confirmed. You can browse the repository, but cannot download any artifacts. I haven't worked at Pentaho / Hitachi for many years now, but my wife does! I'll have her notify the team.

![Screenshot 2024-02-06 at 9 56 46 AM](https://github.com/pentaho/pentaho-reporting/assets/72530/66512086-2cdd-4a86-8c32-2851a23ad800)
![Screenshot 2024-02-06 at 10 01 53 AM](https://github.com/pentaho/pentaho-reporting/assets/72530/98b58616-921c-46f5-a4e0-d86ed7d4ce4a)

**Comment by FlorianCassayre** [comment]
Hi, our builds are failing since yesterday because of that, we're getting HTTP 503 and indeed the UI shows that the license has expired. Any solution in sight?

**Comment by lursel** [comment]
The repositories are up again!

**Comment by wilfriedago** [comment]
Hello ! I've been struggling with accessing the repository url since yesterday.

1. https://repo.orl.eng.hitachivantara.com/ui/native/pnt-mvn/  -- > It routing me to https://repo.orl.eng.hitachivantara.com/ui/login/

2. https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/ -- > It routing me to https://hitachiedge1.jfrog.io/ui/login/

Where to create the login? This used to be publicly available.

3. https://public.nexus.pentaho.org/content/groups/omni/ --> Site Unavailable.

Someone, please help me.

**Comment by wilfriedago** [comment]
> Indeed; what we have done since was to set up a proxy repository to cache the artifacts, that way we don't have to deal with these infrastructure problems.

That's doesn't seem to work ! I'm facing a Jfrog login form and i can fetch artifacts from the repository and that's make my build failiing.

How can i get those credentials ?
