### ISSUE TITLE
Improvement - Context locale override

### ISSUE THREAD

**Issue by Martronic-SA** [pentaho/pentaho-reporting#321]
It should be possible to override the contexts' locale lang with a parameter coming from the datasource.
For example I'm using Pentaho for printing invoces from OpenERP but I can't have my invoices transleted in customer's language. It's always in system language.

The overriden parameter could be in the Report configuration:
environment.designtime.Locale = ${lang} to be evaluated and taken from datasource (or it might be passed from pentaho openerp plugin)
or an additionnal attribute in the master report where it would be possible to pass a parameter.

Thank you!

**Comment by tmorgner** [comment]
Follow this as PRD-3878 on our JIRA system.

http://jira.pentaho.com/browse/PRD-3878
