### ISSUE TITLE
Openerp Data Access and performance problem-Same query executed multiple times 

### ISSUE THREAD

**Issue by MLauri** [pentaho/pentaho-reporting#683]
Hello to all,
I have a tricky problem with report's design and odoo/openerp data access.
It seems that queries via ORM are executed more than one time, causing a significant performance degradation.
I try to describe the problem using a simple example (here http://forums.pentaho.com/showthread.php?195396-Openerp-Data-Access-and-performance-problem-Same-query-executed-multiple-times you can find the .prpt file)

Scenario
Report designer (version 5.4 or 6.0)
Postgresql 9.2
Master report with no datasources, only one inline subreport in the "Report Header" section of the master report.
In the subreport there is only one "Openerp Data Access" datasource, configured with a simple model name (res.bank) that consider only two "search fields" (name and phone, for example). These fields are added into the "Details" section of the subreport.
Entering the preview mode and checking the postgres' log with query logging enabled, I notice that the query on res_bank table is executed three times.

This is a big problem when using more than one subreport at time with complex models.
Is this an issue of the connector?
I appreciate any help you can provide.

**Comment by dkincade** [comment]
Pentaho uses forums (http://forums.pentaho.com) for questions like this. Please post your question out there ..
