### ISSUE TITLE
JavaScript global variables not visible in Query Scripting

### ISSUE THREAD

**Issue by ionutdobre** [pentaho/pentaho-reporting#728]
Hello,

We are using Pentaho Report Designer to generate complex reports and we rely a lot on post processing the query results with JavaScript, but running PRD with java 8 breaks the reports because with the newly JavaScript engine (nashorn) global variables defined in _Global Scripting_ are not visible in _Query Scripting_.

I think the problem is in ```DataFactoryScriptingSupport``` class:

```
if ( globalContext != null ) {
        final Bindings bindings = globalContext.getBindings( ScriptContext.ENGINE_SCOPE );
        this.context.getBindings( ScriptContext.ENGINE_SCOPE ).putAll( bindings );
}
``` 

Since nashorn associates all global variables declared in ```globalContext``` with a _nashorn global object_ (https://wiki.openjdk.java.net/display/Nashorn/Nashorn+jsr223+engine+notes) they will not be visible when they are added to query script context: ```this.context.getBindings( ScriptContext.ENGINE_SCOPE ).putAll( bindings );```.

Possible solution:

```
if ( globalContext != null ) {
        final Bindings bindings = globalContext.getBindings( ScriptContext.ENGINE_SCOPE );
        // this should work since ScriptObjectMirror is implementing Bindings
        Bindings nashornGlobal = bindings.get("nashorn.global");  
        this.context.getBindings( ScriptContext.ENGINE_SCOPE ).putAll(nashornGlobal);
        this.context.getBindings( ScriptContext.ENGINE_SCOPE ).putAll(bindings);
}
```

**Comment by tmorgner** [comment]
Thank you. I filed [PRD-5626](http://jira.pentaho.com/browse/PRD-5626) for this issue. This way this case here can be closed and we can track progress as part of our normal working procedures.
